// Local dev only — copy to js/config.js and fill in values.
// On Vercel, js/config.js is auto-generated by build.js from environment variables.
// js/config.js is gitignored — never commit real credentials.
//
// Supabase credentials: https://supabase.com/dashboard/project/_/settings/api
// Football token: set as FOOTBALL_API_TOKEN in Vercel env vars (stays server-side)

const CONFIG = {
  SUPABASE_URL: 'https://YOUR_PROJECT.supabase.co',
  SUPABASE_ANON_KEY: 'YOUR_SUPABASE_ANON_KEY',
  ADMIN_PIN: '',  // set ADMIN_PIN env var in Vercel; defaults to 'kickoff' if blank
};
